version: '2'
services:
  eclipse:
    image: theskyinflames/eclipse
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /workspace:/workspace
