version: '2'
services:
  eclipse:
    image: theskyinflames/eclipse
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - TERM=xterm
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${ECLIPSE_PLUGINS_DIRECTORY}:/home/developer
      - ${ECLIPSE_WORKSPACE}:/workspace
      - /home/oracle:/home/oracle
    ports:
      - 8080:8080
      - 8085:8085
      - 8009:8009
      - 443:443
