version: '2'
services:
  eclipse:
    image: theskyinflames/eclipse
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${ECLIPSE_PLUGINS_DIRECTORY}/.eclipse-docker:/home/developer
      - ${ECLIPSE_WORKSPACE}:/workspace

