#!/bin/bash

docker run -ti --rm \
           --privileged \ 
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v "`pwd`":/workspace \
           fgrehm/eclipse:v4.4.1
